name: Generate JS script

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
  workflow_dispatch:
    
jobs: 
  build:
  
    runs-on: ubuntu-latest
    
    steps: 
    - name: checkout actions
    - uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v3.1.3
      with:
        python-version: 3.10

    - name: generate script
      run: |
        cd Classical-THBWiki-Character-List
        pip install numpy
        pip install requests

    - name: commit
      run: |
        git config --global user.email abbaccadd0@qq.com
        git config --global user.name abbaccadd0
        git add .
        git commit -m "update" -a
